### ISSUE TITLE
minimal notification should not be pushed if the webchat is already opened

### ISSUE THREAD

**Issue by meelie** [Yeldaai/chat-plugin#109]
1. i opened chat-plugin/test/test.html in my browser in incognito mode (connected to staging fm logistic that has 2 push notification setup on start)
2. i click on the minimal notification bubbleText after the first notication, it opens the webchat
3. The third notification is displayed in minimal mode above the webchat. 
If the webchat is opened, notification should not be added to bubbleText, and it should be only in the webchat 

![image](https://user-images.githubusercontent.com/5340081/145830725-1d35ec89-f155-4b01-b96e-f4a72dfbd1cf.png)

**Comment by vishnu-ravi** [comment]
fixed with https://github.com/Yeldaai/website-chat/pull/489
