### ISSUE TITLE
BUG: Can't open the webchat on Best Western on mobile

### ISSUE THREAD

**Issue by codebynao** [Yeldaai/chat-plugin#124]
**Describe the bug**
Error in console:
`TypeError: this.removeElement is not a function. (In 'this.removeElement("yelda_assistant_bubble_text")', 'this.removeElement' is undefined)`

**To Reproduce**
1. On mobile, go to https://www.bestwestern.fr/
2. Wait for the chat bubble to appear on the right corner
3. Clic on the bubble then on "Discuter avec l'assistant vocal"
4. Nothing happens. The error above appears in the console 

**Expected behavior**

**Environment**
It happens on both iOS and Android so it does not seem to be browser/os related

**Comment by meelie** [comment]
client code is 
yeldaChat.init({settingId: '600e9e10b546c5102ceed404' }) ;
var elementToClick = document.getElementById('voice-bot') ;
elementToClick.addEventListener('click', yeldaChat.openChat) ;
```
We need to bind the yeldaChat
```
yeldaChat.init({settingId: '600e9e10b546c5102ceed404' }) ;
var elementToClick = document.getElementById('voice-bot') ;
elementToClick.addEventListener('click', yeldaChat.openChat.bind(yeldaChat)) ;
```

it fix the JS error 

but there is maybe a css issue to investigate : 
 yelda_container  is in wrapperOptions html element, and i see yelda_container force to 0, 0 
 
![Selection_953](https://user-images.githubusercontent.com/5340081/155538633-2e686f5b-52fd-49e2-8235-e86c5776f997.png)

**Comment by thomasgx** [comment]
I don't know if the issue is related, but the client is now mentionning the problem.
I can see a JS error on the website, in mobile mode : 

![image](https://github.com/Yeldaai/chat-plugin/assets/2161235/f16d8089-5411-40b7-9ae6-56f14a901ac9)

We need to fix it at the earliest now.

**Comment by codebynao** [comment]
JS issue and CSS fixed on the client side with 
```js
yeldaChat.init({settingId: '600e9e10b546c5102ceed404' });
var elementToClick = document.getElementById('voice-bot');
// Ancien code: elementToClick.addEventListener('click', yeldaChat.openChat);
// Fix:
elementToClick.addEventListener('click', yeldaChat.openChat.bind(yeldaChat)); 
```

```
// In on_s_engage.jsp on the client side
.yelda_container #yelda_assistant_bubble_text, .yelda_container #yelda_iframe_container {
 visibility: hidden !important; // <= removed
 font-size: 0;
}
```
