### ISSUE TITLE
Fallback AI didn't work

### ISSUE THREAD

**Issue by Sofia-Zidane** [Yeldaai/chat-plugin#149]
The fallback AI sometimes doesn't work : 
https://app.yelda.ai/a4bde/cannes_croisette/conversations/664f04f14ba6c2588fa6b5df
https://app.yelda.ai/a4bde/cannes_croisette/conversations/6645ff9325df4267f843c265

**To Reproduce**
I can't reproduced it, It's an unexpected behavior

**Expected behavior**
The fallback AI is supposed to give an answer when the NLP confidence is lower than 80%, as set for the callbot Cannes Croisette

**Screenshots**
![image](https://github.com/Yeldaai/chat-plugin/assets/170619503/4f91fe20-3137-4ee4-b892-0e5bd98bab15)

**Additional context**
The fallback AI didn't work when the client was testing ---> https://app.yelda.ai/a4bde/cannes_croisette/conversations/664f04f14ba6c2588fa6b5df

But when I tested it worked --> https://app.yelda.ai/a4bde/cannes_croisette/conversations/6655c5976fcaf9a87251dcc6
 
![image](https://github.com/Yeldaai/chat-plugin/assets/170619503/c99f6fdd-ecab-49ef-b03f-09774e7011ef)

**Comment by meelie** [comment]
Thanks for the links, unfortunately https://app.yelda.ai/a4bde/cannes_croisette/conversations/6645ff9325df4267f843c265 is too old : our logs don't go that far in the past (we have access to 7days)

i searched for https://app.yelda.ai/a4bde/cannes_croisette/conversations/664f04f14ba6c2588fa6b5df but i did not find anything, so next time repost here right away if you face the issue, it will be easier for me to find out

**Comment by meelie** [comment]
note : the issue has nothing to do with this repo, it should be in https://github.com/Yeldaai/office-crons/issues
