### ISSUE TITLE
Update the readme "Using script tags" with direct link to yelda hosted injector files ?

### ISSUE THREAD

**Issue by meelie** [Yeldaai/chat-plugin#2]

**Comment by vishnu-ravi** [comment]
There might be a problem with this point, I have moved webpack build file and source code to this repo, so the yelda hosted injector files may not up to date with the latest version

**Comment by meelie** [comment]
Yup, but we need to provide a bundle for the people not using npm (old websites) : we don't want them to store the lib in local : update would be even worse !
I assigned it to me => i'll take care of it when the latest version will be available on yelda (which is not the case indeed ;) )
