### ISSUE TITLE
While creating a new assistant got a JS error from the webchat injector 

### ISSUE THREAD

**Issue by meelie** [Yeldaai/chat-plugin#26]
**Describe the bug**
While creating a new assistant got a JS error from the webchat injector CF  screenshot (from creation to step 1, after selecting voice)

**Screenshots**
![image](https://user-images.githubusercontent.com/5340081/57623276-be994680-758f-11e9-8f3a-25d613b57441.png)

**Environment**
Staging BO, creating a new assistant

**Comment by d-weber** [comment]
I can't reproduce

**Comment by d-weber** [comment]
Tell me if it's still occur after a hard-refresh :)

**Comment by d-weber** [comment]
Ok did reproduce finally, fixing it on frontend, closing this one
